### Write a function so that the columns of the output matrix are powers of the input vector.

#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def power_matrix(vectr, N, b_increase):
    
    matrix_output = np.ones((vectr.shape[0], N))
    for i in range(N):
        y = i + 1
        if not(b_increase) : y = N - i 
        matrix_output[:,i] = vectr ** y
        
       
    return matrix_output

In [3]:
vector = np.array([3,4,2,5,1])
N = 6
b_increase = False
np. set_printoptions(suppress=True)
print(power_matrix(vector, N, b_increase))

[[  729.   243.    81.    27.     9.     3.]
 [ 4096.  1024.   256.    64.    16.     4.]
 [   64.    32.    16.     8.     4.     2.]
 [15625.  3125.   625.   125.    25.     5.]
 [    1.     1.     1.     1.     1.     1.]]


In [4]:
vector = np.array([3,4,2,5,1])
N = 6
b_increase = True
np. set_printoptions(suppress=True)
print(power_matrix(vector, N, b_increase))

[[    3.     9.    27.    81.   243.   729.]
 [    4.    16.    64.   256.  1024.  4096.]
 [    2.     4.     8.    16.    32.    64.]
 [    5.    25.   125.   625.  3125. 15625.]
 [    1.     1.     1.     1.     1.     1.]]


## Question: Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
# Problem Statement 2:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
# the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [6]:
def moving_average(sequence, k):
    
    n = len(sequence)
    y = []
    
    for i in range(k, n+1):
        y.append(sum(sequence[i-k : i])/k)
        
    return np.array(y)

In [7]:
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
window = 3

np.set_printoptions(precision=2)

print(moving_average(x, window))

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]


In [8]:
x = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
k = 4

print(moving_average(x, k))

[25. 35. 45. 55. 65. 75. 85.]
